project:
  type: website
  output-dir: docs
  
website:
  title: "⬡⬢"
  page-footer: "Copyright 2025, Dave Brocker"
  navbar:
    logo: images/kurbits-hex-logo.svg
    title: false
    right:
      - href: index.qmd
        icon: house
        text: Home
      - courses.qmd
      - href: writing.qmd
        icon: pencil
        text: Writing
      - href: apps.qmd
        icon: terminal
        text: Apps
      
format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true
    code-link: true
    code-overflow: wrap
    code-copy: hover
    code-line-numbers: true

