project:
  type: website
  output-dir: docs
  
website:
  title: "⬡⬢"
  page-footer: "Copyright 2025, Dave Brocker"
  navbar:
    logo: images/kurbits-hex-logo.svg
    title: false
    right:
      - href: index.qmd
        icon: house
        text: Home
      - courses.qmd
      - href: writing.qmd
        icon: pencil
        text: Writing
      - href: tutorials.qmd
        icon: mortarboard
        text: Tutorials
      - href: apps.qmd
        icon: terminal
        text: Apps
      - href: portfolio.qmd
        icon: bar-chart
        text: Portfolio
      - href: research.qmd
        icon: search
        text: Research
      - href: about.qmd
        icon: person
        text: About

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom-dark.scss]
    css: styles.css
    toc: true
    code-link: true
    code-overflow: wrap
    code-copy: hover
    code-line-numbers: true

