project:
  type: website
  output-dir: docs
  
website:
  title: "Dave Brocker"
  twitter-card: true
  site-url: twitter.com
  navbar:
    left:
      - href: index.qmd
        text: Home 
      - about.qmd
      - courses.qmd
      - research.qmd
      - writing.qmd
      - presentations.qmd
      - apps.qmd
      
format:
  html:
    theme:
      light: cosmo
      dark:  [darkly, theme-dark.scss.css]
    css: styles.css
    toc: true
    code-link: true
    code-overflow: wrap
    code-copy: hover
    code-line-numbers: true

