---
output: html_document
---

<br>

##### Click on the Faculty member's name to see their published work and to get an idea of what research is being done in their field.
<br>

#### [Dr. Marya Howell-Carter](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=marya+howell-carter&btnG=&oq=Marya+Howell)
**Areas of Specialization:** <br>Adolescent Therapy, Psychological Concerns in College Students, Family Therapy, Women’s Issues

#### [Dr. Michael Goodstone](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=MS+Goodstone&btnG=)
**Areas of Specialization:**<br> Industrial/Organizational Psychology, clinical applications in organizations, psychological assessment.

#### [Dr. Jennifer Gonder](https://scholar.google.com/scholar?start=0&q=Jennifer+Nieman%E2%80%90Gonder&hl=en&as_sdt=0,33)
**Areas of Specialization:**<br> Industrial/Organizational Psychology; performance evaluation and feedback; leadership development; work motivation; customer satisfaction.

#### [Dr. Sayeed Islam](https://scholar.google.com/citations?user=dpNokP0AAAAJ&hl=en&oi=sra)
**Areas of Specialization:**<br> Customer service, Self-efficacy, Training and Development, proactive personality



#### [Dr. Marla Johnston](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=Marla+Johnston+farmingdale&btnG=)
**Areas of Specialization:**<br> Child Development, Moral Development, Parenting, Discipline, Domain Theory, Adolescent Stress

#### [Dr. Michaela Porubanova](https://farmingdale.academia.edu/MichaelaPorubanova)
**Areas of Specialization:**<br> Cognitive Psychology; Visual Attention and Emotion; Culture and Cognition

#### Dr. Maria Anderson
**Areas of Specialization:**<br> Behavioral Neuroscience, animal models of Alzheimer’s disease, lifestyle interventions and cognitive decline

#### [Dr. Michael Figuccio](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=MJ+Figuccio&btnG=)
**Areas of Specialization:**<br> Behavioral Neuroscience, animal models of Alzheimer’s disease, lifestyle interventions and cognitive decline

#### Bindu Annie Dulock, M.A.
**Areas of Specialization:**<br> Child and Family Psychology, Parenting, Cognitive Behavioral Treatment

#### [Dr. Jason Clarke](https://farmingdale.academia.edu/JasonClarkePhD)
**Areas of Specialization:**<br> Cognitive Psychology, Visual Perception and Cognition, Counsciousness.


